version: "3.9"
services:
  kcp-dev:
    build: https://github.com/fire-ant/kcp.git#main
      
    ports:
      - 6443:6443
    entrypoint: /kcp
    command: start
    volumes:
      - ./kcp:/data/.kcp/
    user: root