version: "3.9"
services:
  kcp-dev:
    build: https://raw.githubusercontent.com/fire-ant/kcp/main/Dockerfile
    ports:
      - 6443:6443
    entrypoint: /kcp
    command: start
    volumes:
      - ./kcp:/data/.kcp/
    user: root